-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for PrintYul.

module PrintYul where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsYul

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsYul.Ident where
  prt _ (AbsYul.Ident i) = doc $ showString i
instance Print AbsYul.HexNumber where
  prt _ (AbsYul.HexNumber i) = doc $ showString i
instance Print AbsYul.YulProgram where
  prt i = \case
    AbsYul.YulObject str yulblock -> prPrec i 0 (concatD [doc (showString "object"), printString str, doc (showString "{"), doc (showString "code"), prt 0 yulblock, doc (showString "}")])

instance Print AbsYul.YulBlock where
  prt i = \case
    AbsYul.YulBlockStmt yulstmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 yulstmts, doc (showString "}")])

instance Print [AbsYul.YulStmt] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsYul.YulStmt where
  prt i = \case
    AbsYul.YulVarDecl yulident yulexpr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 yulident, doc (showString ":="), prt 0 yulexpr])
    AbsYul.YulVarDeclTyped yulident yultype yulexpr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 yulident, doc (showString ":"), prt 0 yultype, doc (showString ":="), prt 0 yulexpr])
    AbsYul.YulVarDeclMulti yulident yulidents yulexpr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 yulident, doc (showString ","), prt 0 yulidents, doc (showString ":="), prt 0 yulexpr])
    AbsYul.YulAssign yulident yulexpr -> prPrec i 0 (concatD [prt 0 yulident, doc (showString ":="), prt 0 yulexpr])
    AbsYul.YulAssignMulti yulident yulidents yulexpr -> prPrec i 0 (concatD [prt 0 yulident, doc (showString ","), prt 0 yulidents, doc (showString ":="), prt 0 yulexpr])
    AbsYul.YulIf yulexpr yulblock -> prPrec i 0 (concatD [doc (showString "if"), prt 0 yulexpr, prt 0 yulblock])
    AbsYul.YulSwitch yulexpr yulcases -> prPrec i 0 (concatD [doc (showString "switch"), prt 0 yulexpr, prt 0 yulcases])
    AbsYul.YulFor yulblock1 yulexpr yulblock2 yulblock3 -> prPrec i 0 (concatD [doc (showString "for"), prt 0 yulblock1, prt 0 yulexpr, prt 0 yulblock2, prt 0 yulblock3])
    AbsYul.YulBreak -> prPrec i 0 (concatD [doc (showString "break")])
    AbsYul.YulContinue -> prPrec i 0 (concatD [doc (showString "continue")])
    AbsYul.YulLeave -> prPrec i 0 (concatD [doc (showString "leave")])
    AbsYul.YulFunDef yulident yultypedidents yulblock -> prPrec i 0 (concatD [doc (showString "function"), prt 0 yulident, doc (showString "("), prt 0 yultypedidents, doc (showString ")"), prt 0 yulblock])
    AbsYul.YulFunDefRet yulident yultypedidents1 yultypedidents2 yulblock -> prPrec i 0 (concatD [doc (showString "function"), prt 0 yulident, doc (showString "("), prt 0 yultypedidents1, doc (showString ")"), doc (showString "->"), prt 0 yultypedidents2, prt 0 yulblock])
    AbsYul.YulExprStmt yulexpr -> prPrec i 0 (concatD [prt 0 yulexpr])
    AbsYul.YulBlockStmt2 yulblock -> prPrec i 0 (concatD [prt 0 yulblock])

instance Print [AbsYul.YulTypedIdent] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsYul.YulTypedIdent where
  prt i = \case
    AbsYul.YulTypedId yulident -> prPrec i 0 (concatD [prt 0 yulident])
    AbsYul.YulTypedIdTyped yulident yultype -> prPrec i 0 (concatD [prt 0 yulident, doc (showString ":"), prt 0 yultype])

instance Print [AbsYul.YulCase] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsYul.YulCase where
  prt i = \case
    AbsYul.YulCaseCase yulliteral yulblock -> prPrec i 0 (concatD [doc (showString "case"), prt 0 yulliteral, prt 0 yulblock])
    AbsYul.YulCaseDefault yulblock -> prPrec i 0 (concatD [doc (showString "default"), prt 0 yulblock])

instance Print AbsYul.YulType where
  prt i = \case
    AbsYul.YulTypeBool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsYul.YulTypeU256 -> prPrec i 0 (concatD [doc (showString "u256")])
    AbsYul.YulTypeU8 -> prPrec i 0 (concatD [doc (showString "u8")])
    AbsYul.YulTypeU32 -> prPrec i 0 (concatD [doc (showString "u32")])
    AbsYul.YulTypeU64 -> prPrec i 0 (concatD [doc (showString "u64")])
    AbsYul.YulTypeU128 -> prPrec i 0 (concatD [doc (showString "u128")])
    AbsYul.YulTypeS256 -> prPrec i 0 (concatD [doc (showString "s256")])

instance Print AbsYul.YulExpr where
  prt i = \case
    AbsYul.YulLitExpr yulliteral -> prPrec i 0 (concatD [prt 0 yulliteral])
    AbsYul.YulIdentExpr yulident -> prPrec i 0 (concatD [prt 0 yulident])
    AbsYul.YulFunCall yulident yulexprs -> prPrec i 0 (concatD [prt 0 yulident, doc (showString "("), prt 0 yulexprs, doc (showString ")")])

instance Print [AbsYul.YulExpr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsYul.YulLiteral where
  prt i = \case
    AbsYul.YulLitNum n -> prPrec i 0 (concatD [prt 0 n])
    AbsYul.YulLitHex hexnumber -> prPrec i 0 (concatD [prt 0 hexnumber])
    AbsYul.YulLitString str -> prPrec i 0 (concatD [printString str])
    AbsYul.YulLitBool -> prPrec i 0 (concatD [doc (showString "true")])
    AbsYul.YulLitFalse -> prPrec i 0 (concatD [doc (showString "false")])

instance Print [AbsYul.YulIdent] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsYul.YulIdent where
  prt i = \case
    AbsYul.YulId id_ -> prPrec i 0 (concatD [prt 0 id_])
