-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Tiny.

module AbsTiny where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Stmt
    = SSeq Stmt Stmt
    | SAssgn Ident Expr
    | SSkip
    | SIf BExpr Stmt Stmt
    | SWhile BExpr Stmt
    | SWhileInv BExpr [Invariant] Stmt
    | SCall Ident Expr
    | SBlock Decl Stmt
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Invariant = Inv Formula
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl
    = DVar Ident Expr
    | DProc Ident Ident Stmt
    | DProcS Ident Ident [SpecEl] Stmt
    | DSeq Decl Decl
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SpecEl = SpecPre Formula | SpecPost Formula
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Formula
    = FormulaDA FormulaD
    | FormulaI Formula Formula
    | FormulaQI [Binder] BExpr Formula
    | FormulaQS [Binder] BExpr
    | FormulaAnd Formula Formula
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FormulaD = FormulaDOr BExpr FormulaD | FormulaDB BExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Binder = ForallB Ident | ExistsB Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BExpr
    = BAnd BExpr BExpr
    | BEq Expr Expr
    | BLeq Expr Expr
    | BGt Expr Expr
    | BNot BExpr
    | BTrue
    | BFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = EPlus Expr Expr
    | EMinus Expr Expr
    | EMul Expr Expr
    | EDiv Expr Expr
    | ENum Integer
    | EVar Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

sif1 :: BExpr -> Stmt -> Stmt -> Stmt
sif1 = \ b1 s1 s2 -> SIf b1 s1 s2

sif2 :: BExpr -> Stmt -> Stmt
sif2 = \ b1 s1 -> SIf b1 s1 SSkip

sblocknd :: Stmt -> Stmt
sblocknd = \ s1 -> s1

formulaA :: Formula -> Formula -> Formula
formulaA = \ f1 f2 -> FormulaAnd f1 f2

formulaDO :: BExpr -> FormulaD -> FormulaD
formulaDO = \ f1 f2 -> FormulaDOr f1 f2

band :: BExpr -> BExpr -> BExpr
band = \ b1 b2 -> BAnd b1 b2

bleq :: Expr -> Expr -> BExpr
bleq = \ e1 e2 -> BLeq e1 e2

bnot :: BExpr -> BExpr
bnot = \ b1 -> BNot b1

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

